apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: jitsi
data:
  PUBLIC_URL: "https://A-B-C-D.nip.io"
  XMPP_SERVER: "prosody"
  XMPP_DOMAIN: "meet.jitsi"
  XMPP_AUTH_DOMAIN: "auth.meet.jitsi"
  XMPP_MUC_DOMAIN: "muc.meet.jitsi"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.meet.jitsi"
  JVB_BREWERY_MUC: "jvbbrewery"
  JVB_PORT: "10000"
  JVB_STUN_SERVERS: "meet-jit-si-turnrelay.jitsi.net:443"
  TZ: "America/New_York"
  JICOFO_AUTH_USER: "focus"
  DISABLE_HTTPS: "1"
  ENABLE_HTTP_REDIRECT: "0"