apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: jvb
        image: jitsi/jvb:stable
        envFrom:
        - configMapRef:
            name: jitsi-config
        - secretRef:
            name: jitsi-secrets
        env:
        - name: JVB_ADVERTISE_IPS
          value: "<FLOATING_IP>"
        - name: XMPP_SERVER
          value: "<PROSODY_CLUSTER_IP>"
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"